// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnBMVMKxducIEDWDnlDpiBBkFejBeAm64',
    appId: '1:900517812169:web:997a69736f6a0b6155ba18',
    messagingSenderId: '900517812169',
    projectId: 'events-747f4',
    authDomain: 'events-747f4.firebaseapp.com',
    storageBucket: 'events-747f4.appspot.com',
    measurementId: 'G-W47T6Y2HLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtiJzhLxHiu2uQiHUgVwEOq7bqIZiacU',
    appId: '1:900517812169:android:e4d360e0a40b739055ba18',
    messagingSenderId: '900517812169',
    projectId: 'events-747f4',
    storageBucket: 'events-747f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_t_FjwQ0-HqooW79B-47y7T_VRL2oE8',
    appId: '1:900517812169:ios:1b1c18fbd757c31b55ba18',
    messagingSenderId: '900517812169',
    projectId: 'events-747f4',
    storageBucket: 'events-747f4.appspot.com',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl_t_FjwQ0-HqooW79B-47y7T_VRL2oE8',
    appId: '1:900517812169:ios:c24555f80fdef1b355ba18',
    messagingSenderId: '900517812169',
    projectId: 'events-747f4',
    storageBucket: 'events-747f4.appspot.com',
    iosBundleId: 'com.example.events.RunnerTests',
  );
}
